project:
  type: website

website:
  title: "Simple Quarto Website Practice"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: ./slides/slides.ipynb
        text: Slides

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true



